### PR TITLE
refactor: remove MD5 from alg example list

### PR DESCRIPTION
**Pull request by danielpeintner**
fixes https://github.com/w3c/wot-thing-description/issues/1362

***
<a href="https://pr-preview.s3.amazonaws.com/danielpeintner/wot-thing-description/pull/1376.html" title="Last updated on Feb 9, 2022, 3:49 PM UTC (96a87da)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/1376/72ddd28...danielpeintner:96a87da.html" title="Last updated on Feb 9, 2022, 3:49 PM UTC (96a87da)">Diff</a>

### CODE REVIEW

**Comment by sebastiankb** [comment]
from today's TD call:
- the text change is ok
- the JSON Schema seem to have a wrong definition for "alg". The enum should be removed and string type should be enough
- @danielpeintner will provide an update, @egekorkan should review the JSON Schema change

**Comment by danielpeintner** [comment]
Note: I first thought we have a similar issue is for `format` in  https://w3c.github.io/wot-thing-description/#bearersecurityscheme

https://github.com/w3c/wot-thing-description/blob/114644ae299e6fe5a466a4966a78e0dc87970093/validation/ext-td-json-schema-validation.json#L1161-L1166

Having said that, I think the issue comes that we have 2 different files. To be honest I am not sure why we have both? @egekorkan  do you know?
* [td-json-schema-validation.json](https://github.com/w3c/wot-thing-description/blob/main/validation/td-json-schema-validation.json)
* [ext-td-json-schema-validation.json](https://github.com/w3c/wot-thing-description/blob/main/validation/ext-td-json-schema-validation.json)

**Comment by egekorkan** [comment]
> Having said that, I think the issue comes that we have 2 different files. To be honest I am not sure why we have both? @egekorkan do you know?

I do not really know but I never change that file but it seems that @mmccool , @sebastiankb and @benfrancis have. It is not used anywhere as far as I know.

**Comment by danielpeintner** [comment]
Note: I reverted the changes done for file ext-td-json-schema-validation.json

see https://github.com/w3c/wot-thing-description/issues/1386

**Review by sebastiankb — APPROVED** [review]

**Comment by sebastiankb** [comment]
from today's TD call decided to merge

**Pull request merged**
