### PR TITLE
Update Link and Form

### PR DESCRIPTION
**Pull request by egekorkan**
I have changed their order according to what @mkovatsc mentioned in the call
I have also added highlighting to specific terms in form and link to increase readability

### CODE REVIEW

**Comment by egekorkan** [comment]
I am not able to resolve conflict since it says that the conflict is too complex. It is only a couple of lines, any ideas why it seems complicated to GitHub?

**Comment by vcharpenay** [comment]
It is because the file was deleted in master while you edited it in this branch. I can resolve it locally.

**Comment by mkovatsc** [comment]
#659 is about to resolve this by copying over your edits to the new file environment.

**Comment by egekorkan** [comment]
# 659 doesn't contain the changes of this PR. In particular, the order of Link and Form isn't changed and the highlighting is also not there. I will wait for the updates of #659

**Comment by egekorkan** [comment]
Can be closed, thank you @sebastiankb

**Pull request closed without merging**
