### PR TITLE
correct <span> element for ComboSecurity assertion and add unique id

### PR DESCRIPTION
**Pull request by Fady222**
This PR solves the issue #1179

***
<a href="https://pr-preview.s3.amazonaws.com/Fady222/wot-thing-description/pull/1184.html" title="Last updated on Jul 1, 2021, 11:12 AM UTC (97fdf03)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/1184/8dda72f...Fady222:97fdf03.html" title="Last updated on Jul 1, 2021, 11:12 AM UTC (97fdf03)">Diff</a>

### CODE REVIEW

**Comment by danielpeintner** [comment]
@ashimura how can we solve the IPR issue with Fady being from the Technical University of Munich (TUM)

**Comment by egekorkan** [comment]
So he will be listed officially from Siemens (like me) soon but in the meantime from TUM. Can we override the IPR checks until then?

**Comment by ashimura** [comment]
Let's talk about the procedure offline on the email thread :)

**Comment by sebastiankb** [comment]
from today's TD call, decided to merge

@Fady222 many thanks

**Pull request merged**
