### PR TITLE
Extend JSON-LD context to allow for round-tripping to/from N-Triples

### LINKED ISSUE #1015: Problems translating TDs from JSON-LD 1.1 to RDF and back
In the discovery group we are facing the problem that if we have a TD expressed in JSON-LD 1.1, and we translate such TD into N-Quads (or any other RDF serialisation), then the only way express the N-Quads data as JSON-LD 1.1 with the same structure of the former is by using a frame. The problem is that, I was not able to find any frame in order to perform this operation in the spec, and thus: I can translate JSON-LD 1.1 to RDF, I can translate RDF back to a valid JSON-LD 1.1 serialisation but TDs do not look like the ones in the documentation (or formerly provided by an user).

For the sake of the explanation let's assume [this TD](https://www.w3.org/TR/wot-thing-description/#simple-thing-description-sample), its N-Quad version would be:

````
<urn:dev:ops:32473-WoTLamp-1234> <http://purl.org/dc/terms/title> "MyLampThing" .
<urn:dev:ops:32473-WoTLamp-1234> <https://www.w3.org/2019/wot/td#hasActionAffordance> _:c14n0 .
<urn:dev:ops:32473-WoTLamp-1234> <https://www.w3.org/2019/wot/td#hasEventAffordance> _:c14n5 .
<urn:dev:ops:32473-WoTLamp-1234> <https://www.w3.org/2019/wot/td#hasPropertyAffordance> _:c14n1 .
<urn:dev:ops:32473-WoTLamp-1234> <https://www.w3.org/2019/wot/td#hasSecurityConfiguration> <https://json-ld.org/playground/basic_sc> .
<urn:dev:ops:32473-WoTLamp-1234> <https://www.w3.org/2019/wot/td#securityDefinitions> _:c14n3 .
_:c14n0 <https://www.w3.org/2019/wot/td#hasForm> _:c14n7 .
_:c14n1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://www.w3.org/2019/wot/json-schema#StringSchema> .
_:c14n1 <https://www.w3.org/2019/wot/json-schema#propertyName> "status" .
_:c14n1 <https://www.w3.org/2019/wot/td#hasForm> _:c14n4 .
_:c14n2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://www.w3.org/2019/wot/json-schema#StringSchema> .
_:c14n3 <https://www.w3.org/2019/wot/td#in> "header" .
_:c14n3 <https://www.w3.org/2019/wot/td#scheme> "basic" .
_:c14n4 <https://www.w3.org/2019/wot/hypermedia#hasTarget> <https://mylamp.example.com/status> .
_:c14n5 <https://www.w3.org/2019/wot/td#hasForm> _:c14n6 .
_:c14n5 <https://www.w3.org/2019/wot/td#hasNotificationSchema> _:c14n2 .
_:c14n6 <https://www.w3.org/2019/wot/hypermedia#forSubProtocol> "longpoll" .
_:c14n6 <https://www.w3.org/2019/wot/hypermedia#hasTarget> <https://mylamp.example.com/oh> .
_:c14n7 <https://www.w3.org/2019/wot/hypermedia#hasTarget> <https://mylamp.example.com/toggle> .
````
Now, [if we serialise these N-Quads as JSON-LD 1.1](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Ftd%2Fv1%22%2C%22id%22%3A%22urn%3Adev%3Aops%3A32473-WoTLamp-1234%22%2C%22title%22%3A%22MyLampThing%22%2C%22securityDefinitions%22%3A%7B%22basic_sc%22%3A%7B%22scheme%22%3A%22basic%22%2C%22in%22%3A%22header%22%7D%7D%2C%22security%22%3A%5B%22basic_sc%22%5D%2C%22properties%22%3A%7B%22status%22%3A%7B%22type%22%3A%22string%22%2C%22forms%22%3A%5B%7B%22href%22%3A%22https%3A%2F%2Fmylamp.example.com%2Fstatus%22%7D%5D%7D%7D%2C%22actions%22%3A%7B%22toggle%22%3A%7B%22forms%22%3A%5B%7B%22href%22%3A%22https%3A%2F%2Fmylamp.example.com%2Ftoggle%22%7D%5D%7D%7D%2C%22events%22%3A%7B%22overheating%22%3A%7B%22data%22%3A%7B%22type%22%3A%22string%22%7D%2C%22forms%22%3A%5B%7B%22href%22%3A%22https%3A%2F%2Fmylamp.example.com%2Foh%22%2C%22subprotocol%22%3A%22longpoll%22%7D%5D%7D%7D%7D&frame=%7B%22%40context%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Ftd%2Fv1%22%2C%7B%22saref%22%3A%22https%3A%2F%2Fw3id.org%2Fsaref%23%22%7D%5D%2C%22%40type%22%3A%22saref%3ALightSwitch%22%7D) (regardless the type of serialisation, i.e., compact, explicit, flattern) the JSON-LD 1.1 will not look like the former one.

In order to obtain the same document after the round trip translation, it is required a frame. Is there a frame in the spec?

### PR DESCRIPTION
**Pull request by vcharpenay**
fixes #1015.

Changes:
 - include index property `td:name` to the `ActionAffordance`, `EventAffordance` and `DataSchema` map (under `uriVariables`).
 - define `td:name` instead of  `jsonschema:propertyName` as an index property for `PropertyAffordance` maps
 - <s>define round-tripping procedure with framing</s>

### CODE REVIEW

**Comment by sebastiankb** [comment]
from today's TD call:
- @mmccool mention it would be good to have framing available for [WoT Directory](https://w3c.github.io/wot-discovery/) specification 
- @vcharpenay will have a look this week

**Comment by vcharpenay** [comment]
Regarding the second item (`td:name` vs. `jsonschema:propertyName` index properties), it seems there is a bug upstream. The following snippet 

```json
{
  "@context": {
    "@version": 1.1,
    "td": "https://www.w3.org/2019/wot/td#",
    "properties": {
      "@id": "td:hasPropertyAffordance",
      "@type": "@id",
      "@container": "@index",
      "@index": "td:name",
      "@context": {
        "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
        "jsonschema": "https://www.w3.org/2019/wot/json-schema#",
        "string": "jsonschema:StringSchema",
        "type": {
          "@id": "rdf:type",
          "@type": "@vocab"
        },
        "properties": {
          "@id": "jsonschema:properties",
          "@container": "@index",
          "@index": "jsonschema:propertyName"
        }
      }
    }
  },
  "properties": {
    "status": {
      "type": "string"
    }
  }
}
```

should yield the following triples

```ttl
_:b0 td:hasPropertyAffordance _:b1 .
_:b1 rdf:type jsonschema:StringSchema .
_:b1 td:name "status" .
```
but the result is

```ttl
_:b0 td:hasPropertyAffordance _:b1 .
_:b1 rdf:type jsonschema:StringSchema .
_:b1 jsonschema:propertyName "status" .
```

with [jsonld.js](https://github.com/digitalbazaar/jsonld.js/) (v3.2.0). In other words, `name` is resolved against the nested context instead of the parent context. I don't know if this is a bug in jsonld.js or if the spec itself is designed this way (which may or may not be intentional).

**Comment by vcharpenay** [comment]
@murloc6 could you check the above example on `rdflib` (Python) to see if the result differs?

**Comment by vcharpenay** [comment]
The third item in the TODO list (round-tripping) deserves a separate pull request. I suggest to **merge this PR as soon as possible**. It will help answer some questions that are partly (but not entirely) solved by the changes done here.

See #1161 and related issues.

**Pull request merged**
