### PR TITLE
Update uriVariable example (21)

### PR DESCRIPTION
**Pull request by egekorkan**
Addresses #910

### CODE REVIEW

**Comment by zolkis** [comment]
Looks good, thanks!

**Comment by egekorkan** [comment]
Here is a rendered version: https://cdn.statically.io/gh/w3c/wot-thing-description/d7c47cfce6df02f162e16164fe9beee1802ebbeb/index.html

**Comment by sebastiankb** [comment]
thanks, here the direct link:

https://cdn.statically.io/gh/w3c/wot-thing-description/d7c47cfce6df02f162e16164fe9beee1802ebbeb/index.html#example-21

**Comment by sebastiankb** [comment]
in the vf2f meeting we decided to merge this PR

**Pull request merged**
