### PR TITLE
style: align formatting for examples

### PR DESCRIPTION
**Pull request by danielpeintner**
so far examples 1 to 7 only

fixes https://github.com/w3c/wot-thing-description/issues/1681

***
<a href="https://pr-preview.s3.amazonaws.com/danielpeintner/wot-thing-description/pull/1698.html" title="Last updated on Sep 28, 2022, 8:08 AM UTC (55432dd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/1698/cf94154...danielpeintner:55432dd.html" title="Last updated on Sep 28, 2022, 8:08 AM UTC (55432dd)">Diff</a>

### CODE REVIEW

**Comment by danielpeintner** [comment]
Note: For reviewing I suggest to use  grafik and "hide whitespace" option to see the actual _visible_ changes..

**Review by sebastiankb — APPROVED** [review]

**Review by sebastiankb — APPROVED** [review]
Is this PR still a draft?

**Comment by danielpeintner** [comment]
w.r.t. resolving conflicts... the *correct one is **with** `<span class="rfc211...` Correct?

**Comment by sebastiankb** [comment]
from today's TD call, decided not to merge

**Pull request closed without merging**
