### PR TITLE
Remove td-unique-identifiers assertion

### PR DESCRIPTION
**Pull request by mmccool**
Since @vcharpenay updated the RDF conversion to generate unique IDs for `@id` based on JSON pointers this (annoying) assertion is no longer necessary.  This PR removes it, and should resolve Issue https://github.com/w3c/wot-thing-description/issues/292.

I also modified several assertions that had '(unique)' in them to just say 'unique', that is, I removed the parenthesis... which I felt gave the assertion a vague meaning.  I still find these assertions a little ambiguous since the scope of the uniqueness is not stated.  With the update by @vcharpenay the scope should just be the map in which the keys are used...  However when we add a "map of ..." to all the objects which are really maps, when we define "map" we should just state that the keys need to be unique within each such map, and that will take care of any remaining ambiguity.

I also fixed a minor capitalization inconsistency.

### CODE REVIEW

**Comment by mmccool** [comment]
Note I added PR https://github.com/w3c/wot-thing-description/pull/437 to resolve the remaining ambiguity noted.

**Comment by sebastiankb** [comment]
there are conflicts

**Comment by mmccool** [comment]
Holding off on merging until I understand what we are doing about aligning with JSON 1.1... although I do think we don't *really* want the old behavior of requiring global uniqueness in the JSON serialization.

**Comment by mmccool** [comment]
Not going to merge as it seems there are some spurious changes against the master now.   Going to redo this PR though since we DO want to remove that assertion.

**Pull request closed without merging**
