### PR TITLE
fix default table entry for observable

### PR DESCRIPTION
**Pull request by sebastiankb**
see #1285

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/pull/1292.html" title="Last updated on Nov 23, 2021, 7:59 AM UTC (8960b61)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/1292/19262cf...8960b61.html" title="Last updated on Nov 23, 2021, 7:59 AM UTC (8960b61)">Diff</a>

### CODE REVIEW

**Review by danielpeintner — APPROVED** [review]
LGTM

**Comment by danielpeintner** [comment]
Note: Something else I noticed which is irrelevant for this PR but maybe can be updated also.

Form items are somewhat strangely split in the table


grafik

**Comment by sebastiankb** [comment]
thanks. New version reorder the default value entries

**Review by danielpeintner — APPROVED** [review]
order looks good now also 👍

**Comment by sebastiankb** [comment]
from today's TD call, decide to merge

**Pull request merged**
