### PR TITLE
Address multiple DataSchema issues

### PR DESCRIPTION
**Pull request by sebastiankb**
This PR updates some JSON Schema / DataSchema issue such as:

- [x] #1101
- [x] #1093
- [x] #1094
- [x] #956

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/pull/1104.html" title="Last updated on May 5, 2021, 3:36 PM UTC (a5a80ea)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/1104/4d08013...a5a80ea.html" title="Last updated on May 5, 2021, 3:36 PM UTC (a5a80ea)">Diff</a>

### CODE REVIEW

**Comment by egekorkan** [comment]
- The text for default says:

>  Supply a default JSON value. The value should validate against the schema in which it resides. 

I think that we should not mention JSON here since all other data schema terms are not for JSON values only. Also, default is one of those terms that is easy to apply to other payload formats like `text/plain`.

Also, the word `schema` should be replaced with Data Schema

- Regarding format:

> It is already removed, i.e. not under discussion anymore. We need a better explanation for this.


- Regarding assuming JSON Schema term in Data Schema:

First I had thought that it was fine but actually it makes the following example weird/incorrect:

```js
{
    "@context": [
        "http://www.w3.org/ns/td",
        "https://schema.org"
    ],
    ...
    "properties": {
        "myProperty": {
            "type": "string", //doesn't matter
            "longitude": -122.08585,
            "forms": [...]
        }
    }
}
```

Since `longitude` is specified without a prefix, according to the spec, this should be understood as a JSON Schema term. It is not totally incorrect since when a term is unknown by a JSON Schema processor, it should just ignore it.

Example from https://schema.org/longitude

**Comment by sebastiankb** [comment]
> Since longitude is specified without a prefix, according to the spec, this should be understood as a JSON Schema term.

The full text is: 
>It is noted that data schema definitions within Thing Description instances are not limited to this defined subset and may use additional terms found in JSON Schema. It is assumed that such additional terms within DataSchema definitions that have not used a prefix have their origin in JSON Schema.

So the 'additional terms' refer to JSON schema terms and the longitude would not make sense here.

**Comment by sebastiankb** [comment]
from today's TD call:
- for default we should provide a note that says that default is annotation 
- fix the conflict
- discuss this next week again

**Comment by sebastiankb** [comment]
I removed the text
>It is assumed that such additional terms within DataSchema definitions that have not used a prefix have their origin in JSON Schema. 

again and provide the text of REC version again. We have to decide if we integrate all missing terms as discovered here #1119 for the next update. If so we can remove this paragraph for the CR then.

**Comment by sebastiankb** [comment]
from today's TD call we decided to merge

**Pull request merged**
