### PR TITLE
Explain multiple inputs

### LINKED ISSUE #913: Improve the text on Action parameters (vs input)
The current [description](https://www.w3.org/TR/wot-thing-description/#actionaffordance) of representing Action parameters in the TD is too laconic and creates [misunderstandings](https://github.com/w3c/wot-scripting-api/pull/218#discussion_r438014726).

The text should say how is it possible/recommended to represent multiple inputs to Actions,
for instance by using an [ObjectSchema](https://www.w3.org/TR/wot-thing-description/#objectschema). 

But that would clash with representing a single parameter that is an object. How does an implementation know that an object in the TD Action `input` is meant as a single object parameter, or was meant as multiple parameters made from the members of the object?

### PR DESCRIPTION
**Pull request by egekorkan**
fixes #913

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/pull/1822.html" title="Last updated on May 17, 2023, 10:21 AM UTC (2bb0add)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/1822/d4639d8...2bb0add.html" title="Last updated on May 17, 2023, 10:21 AM UTC (2bb0add)">Diff</a>

### CODE REVIEW

**Comment by egekorkan** [comment]
Call of 17.05: @zolkis if you can have a quick look, it would be nice. We can quickly merge if you are ok with it.

**Comment by zolkis** [comment]
This PR doesn't change any meaning, it just adds explanation, right? 
If the question is if we can use this in Scripting API algorithms -- yes, we can.
For WebIDL, these would mostly translate as `any`, plus the algorithmic steps - instead of union types.

**Comment by zolkis** [comment]
We define them as `any` here: https://w3c.github.io/wot-scripting-api/#the-interactioninput-type 
Of course the PR can be merged, thanks.

**Review by zolkis — APPROVED** [review]

**Comment by zolkis** [comment]
@danielpeintner PTAL

**Pull request merged**
