### PR TITLE
rename required to tmRequired + top level definition 

### PR DESCRIPTION
**Pull request by sebastiankb**
also see #1080

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/pull/1092.html" title="Last updated on Apr 21, 2021, 1:32 PM UTC (a33652b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/1092/24c2bf8...a33652b.html" title="Last updated on Apr 21, 2021, 1:32 PM UTC (a33652b)">Diff</a>

### CODE REVIEW

**Comment by egekorkan** [comment]
I see some issues:
- The reference to JSON Pointer seems to be missing
- 10.4 still uses `required`. In the meantime, 10.4 has typos and assertive words like have to, must that are not RFC assertions
- Title of the example uses `required`
- I think that it is not 100% clear that the pointer should resolve in the affordance object/map, i.e. the following: 

> To guarantee the implementation of particular kind of interaction models, Thing Model definitions MUST use the JSON member name tmRequired as JSON array at the top level that provides JSON Pointer references to the required interaction model definitions. 

Should be split into multiple assertions, something like:

> To guarantee the implementation of particular kind of interaction models, Thing Model definitions MUST use the JSON member name tmRequired. `tmRequired` MUST be a JSON array at the top level.  It MUST provide JSON Pointer references to the required interaction model definitions. The JSON Pointers MUST resolve to an entire interaction affordance Map definition.

This way, all of them can be separately tested and also understood by readers.

**Comment by sebastiankb** [comment]
@egekorkan many thanks. I updated the text.

>10.4 still uses required. In the meantime, 10.4 has typos and assertive words like have to, must that are not RFC assertions

@relu91 can you take this point also in your PR #1095

**Comment by relu91** [comment]
> @relu91 can you take this point also in your PR #1095

Renamed and the _assertive typos_ should be already fixed. ✔

**Review by relu91 — COMMENTED** [review]
Did you evaluate to use a `json-ld` prefix instead of changing `required` to `tmRequired`?. With `json-ld` we could achieve the same in a more consistent pattern:
```js
{
    "@context": ["http://www.w3.org/ns/td",{
       "tm": "http://www.w3.org/ns/td"
     }], 
    "@type" : "tm:ThingModel",
    "title": "Lamp Thing Model",
    "description": "Lamp Thing Description Model",
    "tm:required": [
        "#/properties/status",
        "#/actions/toggle"
    ],
    "properties": {
        "status": {
            "description": "current status of the lamp (on|off)",
            "type": "string",
            "readOnly": true
```

The downside is that we have to force implementers to use `tm` as a prefix otherwise non-json-ld processors would not understand.

**Comment by sebastiankb** [comment]
I see the advantages of this tm: approach and may show a clear separation what belongs to TD data model and TM data model. The disadvantage would be that tm: context would be very small, as we would only have tm:required and tm:Ref in it. For now, I would keep this in the TD model and have it as tmRequired. For the WoT 2.0 version, maybe we can think about a clearer separation and the TM itself will be defined in a separate document.

**Comment by sebastiankb** [comment]
From today's TD call:
- not ready to merge
- it seems it make sense that we introduce an own namespace for TM
- tmReference can be defined as tm:reference
- this should be also true for tmRef #1090

**Comment by sebastiankb** [comment]
from today's TD call: merge this PR

**Pull request merged**
