### PR TITLE
Update Implementation Report and Prep for CR

### PR DESCRIPTION
**Pull request by mmccool**
- copy index.html to publications/ver11/5-cr
- copy test results to publication/ver11/5-cr/testing
- change status to CR
- set CR end date to 2023-01-11 as discussed in main call
- inline atrisk.css
- generate static.html by exporting from ReSpec
- generate Overview.html using htmltidy: **this is the version to be published**
- update implementation report editors (now McCool, Ege, and Fady)
- edited report template so it is suitable for CR (previously it was for PR), states current policy on optional features, has correct dates, etc.
- modified the report generator so it pulls from publication/ver11/5-cr/Overview.html, i.e. after ReSpec static export, meaning the assertions in the report now have things like section references filled in correctly
- resynced acks and editors changes (and updated the export and tidying process)
- fixed small typo in acks: "special thank" -> "specially thank" (thank is used as a verb here, so you have to use an adverb to modify it).  This change was in index.template.html (and index.html, after rendering update)

***
<a href="https://pr-preview.s3.amazonaws.com/mmccool/wot-thing-description/pull/1730.html" title="Last updated on Oct 26, 2022, 1:52 PM UTC (284b262)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/1730/85d5165...mmccool:284b262.html" title="Last updated on Oct 26, 2022, 1:52 PM UTC (284b262)">Diff</a>

### CODE REVIEW

**Comment by k-toumura** [comment]
- [Rendered version of Overview.html (0ccc819)](https://cdn.statically.io/gh/w3c/wot-thing-description/0ccc81977d357b8363e391353cb8a0c741ac3143/publication/ver11/5-cr/Overview.html)
- [Rendered version of IR (0ccc819)](https://cdn.statically.io/gh/w3c/wot-thing-description/0ccc81977d357b8363e391353cb8a0c741ac3143/publication/ver11/5-cr/testing/report11.html)

**Comment by mlagally** [comment]
I have generated an overview table of all testing results for TD.

https://github.com/w3c/wot-thing-description/pull/1733

The CSV file all-TD-assertions.csv in that PR is a combination of the implementation reports that are contained in the testing/inputs/results directory.

The list of all assertions is the combiation of all assertion ids from the individual contributions.
Cells marked as XXXX are assertions that are not contained in the respective input.

A couple of observations:

- The TD specification contains 165 assertions (all-assertions.csv), however many input files contain >400. Why?
- Some responses look as if they were submitted during the 1.0 version of the specification and never were updated. It is questionable whether these should be used as implementation proof for the TD 1.1 specification.
- Several distinct responses were provided by the same companies and should not be counted as individual contributions. There should be rather a single combined implementation report from each company. 
- Some responses by companies that are no longer members of the WG are also present - these should be excluded.

**Comment by wiresio** [comment]
We already submitted an implementation report and it got lost. Please see: https://github.com/w3c/wot-testing/pull/384

**Comment by sebastiankb** [comment]
Thank you very much for this PR.  As chair of the TD task force, I recommend moving to the Candidate Recommendation (CR) phase with the TD1.1 specification. The [implementation report](https://w3c.github.io/wot-thing-description/testing/report11.html) shows a high adoption rate of TD1.1 features. Features that have only one or no implementation will be labeled [at-risk](https://w3c.github.io/wot-thing-description/#sotd) in the TD1.1 CR specification. To the best of my knowledge, there is no [blocking issue](https://github.com/w3c/wot-thing-description/labels/BLOCKER) in the TD repository. The most recent issue mentioned in Issue ["by CR transition"](https://github.com/w3c/wot-thing-description/issues?q=is%3Aissue+is%3Aopen+label%3A%22by+CR+transition%22) could be solved and/or answered.

**Comment by sebastiankb** [comment]
from today's TD call:
- in the main call there is a group resolution to go to Candidate Recommendation of the Thing Description 1.1 specification
- decide to merge this PR

**Pull request merged**
