### PR TITLE
WIP: Add proof and proofChain sections

### PR DESCRIPTION
**Pull request by mmccool**
For signing TDs, add proof and proofChain sections consistent with Linked Data Signatures (https://w3c-ccg.github.io/ld-proofs/#linked-data-signatures).   WIP, need to discuss:
1. How to declare objects defined in a different spec.  we don't want to redundantly repeat the definition.
2. How to handle context; context file not yet updated
3. How to achieve backward compatibility... explicit extension context needed in some cases?
4. Need to definite normalized serialization order for signatures.  Need to be careful about items where order is defined as not mattering, but does, eg actions, properties, etc.  Also need to revisit whether order matters for forms.  Propose introducing a "Set" abstract data type to make this clearer (syntactically it would still be an array, though).

Satisfies https://github.com/w3c/wot-thing-description/issues/940

***
<a href="https://pr-preview.s3.amazonaws.com/mmccool/wot-thing-description/pull/943.html" title="Last updated on Feb 24, 2021, 3:23 PM UTC (8b587cb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/943/58f543f...mmccool:8b587cb.html" title="Last updated on Feb 24, 2021, 3:23 PM UTC (8b587cb)">Diff</a>

### CODE REVIEW

**Comment by sebastiankb** [comment]
lets discuss this in tomorrow's TD meeting

**Comment by mmccool** [comment]
Note the LD-Proofs spec allows some fields to be open-ended, and I think for interoperability we want to support only a finite set of options.

**Comment by sebastiankb** [comment]
from today's TD call:
- not ready to merge
- topic to discuss with the JSON-LD group during TPAC

**Comment by sebastiankb** [comment]
from today's TD call:
- going to merge this PR
- mark this as "at risk"
- @mmccool will resolve the conflicts and will merge this PR

**Comment by mmccool** [comment]
Ugh, this is going to be difficult to update to use the new render script since the original PR just modified index.template.html directly and did not have any ontology definitions... since one of the things I wanted to resolve was grabbing those definitions from the DID/VC WG.   That will have to wait until we meet with them to sort out so for now I think we have to defer this until after the FPWD.

**Comment by iherman** [comment]
Note: we must be careful that the LD Signature document is not (yet) normative. There are initial discussions to, eventually, set up a Working Group whose goal would be to provide a standard in that direction (including a canonicalization algorithm for linked data, which is the hard nut to crack for such a WG), but there is no specific plan, charter proposal, etc, yet for this.

Here is a place where the evolution can be followed: https://github.com/w3c/strategy/issues/116

**Comment by sebastiankb** [comment]
From today's TD call:
- this PR is still valid, however, the PR is not fixable
- best way is to create a new PR and close this one
- @mmccool will take care on this

**Comment by mmccool** [comment]
Looks like there has been no further progress on a canonical form for JSON-LD so I think we should proceed assuming such will not be done in time.  Also, as pointed out above, LD-PROOFS is not normative so I can't just cite it as a definition like in my original PR.  Rather I will have to include all the necessary definitions in the TD document itself so it is self-contained.

**Comment by sebastiankb** [comment]
from today's TD call:
- close this PR since the base line is outdated
- @mmccool creates a new PR (will be based on the issue #940)

**Pull request closed without merging**
