### PR TITLE
WIP: Updated RDF vocabularies

### PR DESCRIPTION
**Pull request by vcharpenay**
- added axioms to vocabs
 - modified JSON-LD context
 - added examples in the onto HTML doc of each vocab
 - updated RDF example in wot-thing-description

To do:
 - [x] add more examples on annotating TDs with SOSA/SSN
 - [x] add more examples on equivalences between affordances 
 - [x] finish axiomatization of `hyperm` and provide more examples for forms
 - [x] fix `templates.txt` to render all OWL axioms properly
 - [ ] fix SHACL validation file

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/pull/744.html" title="Last updated on Dec 9, 2019, 12:17 PM UTC (c5ce7ac)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/744/a80bdd2...c5ce7ac.html" title="Last updated on Dec 9, 2019, 12:17 PM UTC (c5ce7ac)">Diff</a>

### CODE REVIEW

**Comment by vcharpenay** [comment]
Rendered versions of the ontology documentations can be found here:
- [TD ontology](https://cdn.staticaly.com/gh/w3c/wot-thing-description/onto-examples/ontology/td.html?env=dev)
- [JSON schema in RDF](https://cdn.staticaly.com/gh/w3c/wot-thing-description/onto-examples/ontology/jsonschema.html?env=dev)
- [WoT security ontology](https://cdn.staticaly.com/gh/w3c/wot-thing-description/onto-examples/ontology/wotsec.html?env=dev)
- [Hypermedia controls ontology](https://cdn.staticaly.com/gh/w3c/wot-thing-description/onto-examples/ontology/hyperm.html?env=dev)

**Comment by takuki** [comment]
What would be an appropriate description of this changes when we describe what we changed in the Recent Changes section?

Can @vcharpenay provide a few sentences to add to the Recent Changes section?

**Comment by mkovatsc** [comment]
@vcharpenay considering the required changes for PR transition, many conflicts, etc., please manually move over your content to the new file versions created through https://github.com/w3c/wot-thing-description/pull/783

This would also mean closing this now outdated PR.

**Comment by mmccool** [comment]
HTML Diff confirmed: no changes, as expected.
https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fwot-thing-description%2Fmaster%2Findex.html&doc2=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fwot-thing-description%2Fpre-pr-branch%2Findex.html#sec-security-vocabulary-definition

**Pull request merged**
