### PR TITLE
Update Test results post-CR (using only TDs provided by implementers)

### PR DESCRIPTION
**Pull request by mmccool**
Note: still waiting to merge with duplicate id fixes from @ashimura; however, I will deal with those in a separate PR as I need to update these test results now.

- Recent test run with new AssertionTester results and using CR draft
- Using only validated test TDs provided by implementors

Also addresses issues
- https://github.com/w3c/wot-thing-description/issues/701 
- https://github.com/w3c/wot-thing-description/issues/702
- https://github.com/w3c/wot-thing-description/issues/710

Rendered Implementation Report Draft: https://cdn.statically.io/gh/mmccool/wot-thing-description/master/testing/report.html?env=dev

### CODE REVIEW

**Comment by mmccool** [comment]
So, there are a LOT of errors now, i.e. lines with 0-0-0-0 results.  What happened?  Was there a mass renaming of ids?   Are partial test results not being generated if TDs don't validate, e.g. because of the "title" change?

**Comment by mmccool** [comment]
Note that a list of TDs that are failing validation can be generated by doing a "grep" on the output of the update.sh script, which I have checked in as "wot/testing/tests/2019-05/update.log":
```
git clone https://github.com/w3c/wot.git
cd wot/testing/tests/2019-05
grep -B 1 "ERROR" update.log
```

**Comment by egekorkan** [comment]
An invalid td (such as not having title) will cause a lot of problems in the beginning and stop the validation. I am guessing it is because of that since the playground examples pass. The examples are [here](https://github.com/thingweb/thingweb-playground/tree/master/WebContent/Examples/Valid)

**Comment by mmccool** [comment]
Yes, I figured the invalid TDs (and they were basically ALL invalid) were causing the problem.   To test, I updated all Intel TDs to pass validation and the results are much more reasonable.   But everyone needs to finish their updates.   For the record, here is what I had to fix:
- "name" -> "title" in Thing
- "lastModified" -> "modified" in Thing (note also that DateTime needs to fully satisfy the XML DateTime schema.  In particular notice that seconds in the time are mandatory...)
- Update the mandatory context reference

**Comment by mmccool** [comment]
So the Intel TDs can now also be used as "valid" examples.

**Comment by mmccool** [comment]
I will still leave this as WIP until everyone updates their TDs so they validate.   Hopefully people can do this before the Wed call.   One of use should send an email to the group reminding people to do this.   Ege, can you do that, and point to the playground?   I will take care of merging any PRs updating inputs and will rerun the tests as I see new results...

**Comment by egekorkan** [comment]
An email is sent to the WG with necessary informations

**Comment by sebastiankb** [comment]
Siemens just updated their TDs

**Comment by mmccool** [comment]
Thanks.  Panasonic also updated their TDs.   I manually updated the Oracle and Fujitsu TDs to get a more complete report but as these are not implementor-provided updates I created a separate PR(s) for that(those).

**Pull request merged**
