### PR TITLE
Revision of Section 6

### LINKED ISSUE #609: JSON name vs member and other corrections
When talking about the JSON serialization, the term "name" only refers to the identifier without the value. The term "member" refers to the whole field with value identified by a name.

The usage of those terms is partly incorrect throughout the document. There are also other incorrect statements in Section 6 such as "the type MUST be serialized as".

I am working on a PR, as documenting here was almost more work...

### PR DESCRIPTION
**Pull request by mkovatsc**
This PR fixes #609 , #607, and #606.

### CODE REVIEW

**Comment by mkovatsc** [comment]
Missing revision of 6.2.7, 6.2.9, and 6.2.10.

**Comment by mkovatsc** [comment]
Finished pass over 6.2.7, 6.2.9, and 6.2.10.

**Comment by mkovatsc** [comment]
This PR is already an improvement. However, it opened new issues filed in #615, #613, #612, #611, #608, #607.

Fixed issues are #606 and #609.

**Comment by mkovatsc** [comment]
Also fixed change log, no more ReSpec warnings.

**Comment by mkovatsc** [comment]
@mmccool confirmed in #612 the the changes to security are correct.

@mmccool, could you quickly comment of the other assertion text changes are also good? We should merge soon to be able to continue the sprint...

**Comment by sebastiankb** [comment]
thanks @mkovatsc & @vcharpenay

**Pull request merged**
