### PR TITLE
feat: include JSON schema to index.html

### PR DESCRIPTION
**Pull request by danielpeintner**
fixes https://github.com/w3c/wot-thing-description/issues/1004

***
<a href="https://pr-preview.s3.amazonaws.com/danielpeintner/wot-thing-description/pull/1006.html" title="Last updated on Nov 20, 2020, 10:50 AM UTC (af31ca5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/1006/4825f6b...danielpeintner:af31ca5.html" title="Last updated on Nov 20, 2020, 10:50 AM UTC (af31ca5)">Diff</a>

### CODE REVIEW

**Comment by sebastiankb** [comment]
if I see this correctly, the new terms are missing in the JSON Schema

- multipleOf (integer and number schema)
- minLength + maxLength (sting schema)
- contentEncoding + contentMediaType (DataSchema)
- ComboSecurityScheme with oneOf and allOf

**Comment by egekorkan** [comment]
Combo is introduced in #944 and it is available. Providing fix for the other ones

**Comment by danielpeintner** [comment]
> if I see this correctly, the new terms are missing in the JSON Schema

I think the updates to JSON Schema should probably be another follow-up PR. This PR purely includes the file as is...

**Comment by sebastiankb** [comment]
@ashimura 
I will merge this PR in the hope that it will be included in the FPWD version.

**Review by sebastiankb — APPROVED** [review]

**Pull request merged**
