### PR TITLE
Implementation Report Update - Dec 2022

### PR DESCRIPTION
**Pull request by mmccool**
Include new results from Dec 2022 Testfest.

### CODE REVIEW

**Comment by k-toumura** [comment]
[Rendered version (c324c90)](https://cdn.statically.io/gh/w3c/wot-thing-description/c324c905e77e7da59cb940bc21c11caafb280c5c/testing/report11.html)
Number of at-risk assertions: 25.

**Comment by mmccool** [comment]
Number of at-risk assertions: 22.

**Comment by k-toumura** [comment]
[Rendered version (c6e3dde)](https://cdn.statically.io/gh/w3c/wot-thing-description/c6e3dde3b5cbbaae78aab70bc98e09d59e6575af/testing/report11.html)

**Comment by mmccool** [comment]
As of the final update, there are now only 18 at-risk assertions.  However, the playground does not seem to be picking up the client flow implemented by wot-experimental, which should resolve two more assertions, at least.  So once we resolve that issue I will make another PR to update the report.  However, we plan to merge this so it can count as the "Testfest result".

**Pull request merged**
