### PR TITLE
Mark and Define Maps

### PR DESCRIPTION
**Pull request by mmccool**
This PR attempts to resolve Issue https://github.com/w3c/wot-thing-description/issues/345 by adding a rendering rule to templates.txt for specific vocabulary terms, namely: properties (both the InteractionPattern/InteractionAssertion one and the DataSchema one), actions, events, securityDefinitions, and uriVariables.   Note that definitions and titles are NOT marked as "map of" since MultiLanguage is itself a container with specific rules on the keys used.

The templates.txt lists the specific values this applies to.  There may be a more elegant way to handle this, eg by defining a container class somewhere.   If so, feel free to suggest an improvement to this rule, but this gets the job done.

There is also a definition of "map of" at the top of the Core Vocabulary Definition section.   I also put in a definition of "array of" here.   [EDITED] These definitions are intentionally abstract since other constraints or conventions (for example, that keys should be JSON names, or that arrays or maps should not be empty and should simply be omitted if there are no elements, or that arrays of one element can be replaced with that element) should be listed in the Serialization section.

### CODE REVIEW

**Comment by takuki** [comment]
The fix looks comprehensive. Also, the paragraph defining "Map of X" looks very nice!

**Comment by vcharpenay** [comment]
See PR #445 (already merged) that made the appropriate changes in the table. I rely on the context definitions in `/context` instead of hard-coding values in `templates.txt`. It is maybe more robust to changes.

I haven't textually defined "map of", thanks for that. Can you revert your changes in `templates.txt` and merge the rest?

**Comment by mmccool** [comment]
OK, I will revert my changes, since @vcharpenay seems to have fixed the rendering of maps in a better way, I will update this PR to include only the paragraph defining "map of" and "array of", and merge.

**Comment by mmccool** [comment]
No longer needed, @vcharpenay addressed already, so am going to close this PR without merging.   However I did add the paragraph defining what "map of" and "array of" mean in a separate PR.

**Pull request closed without merging**
