### PR TITLE
Fix definition of multipleOf in TD schema

### PR DESCRIPTION
**Pull request by JKRhb**
In #1186 I noticed (among other issues) that the current definition of multipleOf in the JSON schemas does not work as expected. So far the following (TM) definition would be invalid:

```json
{
    "@context": ["http://www.w3.org/ns/td"],
    "@type": "tm:ThingModel",
    "properties": {
        "foo": {
            "title": "Invalid",
            "multipleOf": 1
        },
        "bar": {
            "title": "Invalid",
            "multipleOf": 2.0
        },
        "baz": {
            "title": "Valid, because not an integer",
            "multipleOf": 2.2
        }
    }
}
```

This PR replaces the `oneOf` in the definitions of `multipleOf` with an `anyOf` and adds an `exclusiveMinimum` of 0 to align the schema more closely to the [specification](https://w3c.github.io/wot-thing-description/#td-vocab-multipleOf--NumberSchema) that states:

> The value must [be] strictly greater than 0.

### CODE REVIEW

**Review by egekorkan — APPROVED** [review]

**Comment by egekorkan** [comment]
Thanks! :)

**Comment by JKRhb** [comment]
> Thanks! :)

Thank you for the approval! :)

I am also adding some (potential) fixes to the TM generation script at the moment and would soon open a PR that maybe requires a bit more discussion in the working group. I hope this approach is okay for you, otherwise let me know :)

**Comment by danielpeintner** [comment]
@egekorkan I am just wondering.... do we have some kind of tests?
e.g., JSON instances that fail/pass w.r.t. the TD/TM schema?
I think having such (automatic) tests would be *very* beneficial

**Review by relu91 — APPROVED** [review]
By the way, the PR does also a small refactoring of the `additionalResponses` term. Now the term refers to a global definition called `additionalResponsesDefinition` (which is good). Well done!

**Comment by egekorkan** [comment]
@danielpeintner wrote:

> @egekorkan I am just wondering.... do we have some kind of tests?
e.g., JSON instances that fail/pass w.r.t. the TD/TM schema?
I think having such (automatic) tests would be very beneficial

So I do have tests for TDs at playground at: https://github.com/thingweb/thingweb-playground/tree/master/packages/core/examples  . These are executed at each PR. Ideally, each change to the TD schema is reflected there and tested automatically.

I will also add TM tests since obviously there are wrong things happening everywhere.

**Comment by JKRhb** [comment]
> By the way, the PR does also a small refactoring of the `additionalResponses` term. Now the term refers to a global definition called `additionalResponsesDefinition` (which is good). Well done!

I think this has actually already been part of the TD schema and is only integrated in this PR because of the regeneration of the TM schema so I can't take credit for that ;) Speaking of which, however, I was thinking about refactoring `multipleOf` as a global definition. Would this be a useful addition to this PR?

**Comment by JKRhb** [comment]
> I was thinking about refactoring `multipleOf` as a global definition. Would this be a useful addition to this PR?

I added such a refactoring now in 902c813a7c6280fc40dd522044e2e7eb783e5398

**Review by sebastiankb — APPROVED** [review]

**Comment by sebastiankb** [comment]
from today's TD call:
- we decided to merge this PR, @JKRhb many thanks
- @JKRhb are you interested for applying as invited expert? Would be cool ;-)

**Comment by JKRhb** [comment]
> * @JKRhb are you interested for applying as invited expert? Would be cool ;-)

Thank you very much for this opportunity! :) I will hand in an application soon :)

**Pull request merged**
