### PR TITLE
TM Schema generation

### PR DESCRIPTION
**Pull request by egekorkan**
I have currently started with the requirements and will be pushing my code to this PR

### CODE REVIEW

**Comment by egekorkan** [comment]
I have added the removal of required. The comments are also added and some questions:
- Should the `required` term and thus its value removed or should its value be replaced by `[""]` as to make sure that nothing is required.

**Comment by egekorkan** [comment]
One important question, is the following allowed in a TM? (let's say that this a DataSchema

```js
"type":"object"
"properties":"{{}}"
```

Similarly, is the following allowed in a TM?

```js
@context: "...",
"actions":"{{}}",
"events":"{{}}"
```

**Comment by danielpeintner** [comment]
> One important question, is the following allowed in a TM? (let's say that this a DataSchema)

I would say both are *not* allowed. 
properties/actions/events require a named object....

**Comment by egekorkan** [comment]
@danielpeintner I have also thought the same but the spec is currently very open about this. I will open an issue

**Comment by sebastiankb** [comment]
From today's TD call:
- we were not sure if the PR is still in wip
- we will merge next week then

**Comment by egekorkan** [comment]
> we were not sure if the PR is still in wip

It is marked as draft, so still WIP

**Review by relu91 — APPROVED** [review]
The algorithm sees fine to me, but I agree that a TM model that looks like this:
```js
{
  "@context": "...",
  "actions":"{{}}",
  "events":"{{}}"
}
```
does not really make sense, plus you could obtain the same by just omitting the keywords:
```js
{
  "@context": "...",
}
```
Right? Probably the same is true for `securityDefinitions`:

```js
{
    securityDefinitions: "{{}}"
}
```

**Comment by egekorkan** [comment]
I also think the same. Keys whose values are objects or arrays can be simply omitted

**Comment by egekorkan** [comment]
I have pushed my non working string replacement method. It is not used at the moment but I am working on it. The recursion does not work and needs some good-old debugging

**Comment by egekorkan** [comment]
Ready for testing/merging. Validates all the TM examples in the current spec.

In the end, I gave up on the _elegant_ recursion but manually wrote where the replacements should occur ^^

**Comment by sebastiankb** [comment]
From today's TD call we will merge the schema. Will be a good input for testing TMs during PlugFest.

**Pull request merged**
