### PR TITLE
fix titles and descriptions type problem + default value entries for security in

### PR DESCRIPTION
**Pull request by sebastiankb**
also see #1137

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/pull/1275.html" title="Last updated on Nov 17, 2021, 3:54 PM UTC (2ba9916)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/1275/ce4cba4...2ba9916.html" title="Last updated on Nov 17, 2021, 3:54 PM UTC (2ba9916)">Diff</a>

### CODE REVIEW

**Review by danielpeintner — CHANGES_REQUESTED** [review]
NOTE: I checked the [rendered version](https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/pull/1275.html).

There are still some issues

### 5.3.1.1 Thing

https://w3c.github.io/wot-thing-description/#thing

In the REC document we used to have MultiLanguage for titles and description. Now it is Map of MultiLanguage 


### 5.3.1.2 InteractionAffordance
https://w3c.github.io/wot-thing-description/#interactionaffordance

* In the REC document we used to have MultiLanguage for titles and description. Now it is Map of MultiLanguage


### 5.3.2.1 DataSchema

https://w3c.github.io/wot-thing-description/#dataschema

In the REC document we used to have MultiLanguage for titles and description. Now it is Map of MultiLanguage 



### 5.3.3.4 DigestSecurityScheme
https://www.w3.org/TR/wot-thing-description/#basicsecurityscheme

qop is "optional" now, used to be "with default"



### 5.3.3.6 BearerSecurityScheme
https://www.w3.org/TR/wot-thing-description/#bearersecurityscheme
alg is optional now, used to be with default
format is optional now, used to be with default

**Comment by sebastiankb** [comment]
many thanks. I just provided a new version

**Review by danielpeintner — APPROVED** [review]
LGTM

**Comment by sebastiankb** [comment]
from today's TD call, decided to merge

**Pull request merged**
