### PR TITLE
Additional Security and Privacy Considerations

### LINKED ISSUE #1405: Consolidate Security and Privacy Considerations (moving IANA security considerations)
There are security and privacy considerations listed under the IANA considerations that are not listed under the Security Considerations and Privacy Considerations sections, and there are also similar ones that are not cross-referenced.  In addition there are assertions under the IANA section (which appears to be normative) but not under the Security and Privacy sections, which are informative.  There is also an additional consideration, about the sanitization of strings drawn from TDs when used in templates, which is different than any already listed under the IANA considerations (although it is similar to the eval() issue, it is not the same), but seems like it should be part of the IANA considerations also.

Security and Privacy reviews expect the security and privacy considerations to be consolidated.

I propose we:
- Make the Security Consideration and Privacy Considerations sections normative.
- Move the Security and Privacy considerations under the IANA considerations down to the appropriate S&P section, replacing or updating any existing text for similar considerations.
- Adding references to the appropriate S&P Considerations from the IANA considerations.
- Add *normative* assertions as appropriate to other security and privacy considerations, but at least for the string sanitization one to be consistent with the other assertions from existing the IANA section.
- Review the document and consolidate any other security and privacy considerations hiding in other sections

### PR DESCRIPTION
**Pull request by mmccool**
New security and privacy considerations:
- [x] Script Injection security risk.  Related to Issue #1401.  Includes some text under discussion of language handling point out that since it is expected that systems generating HTML will sanitize strings from TDs that HTML cannot be depended upon to control rendering, i.e. by setting initial text direction.
- [x] ID Metadata privacy risk.  Resolves https://github.com/w3c/wot-thing-description/issues/1216
- [x] Vulnerability Auditing security risk (there is an issue for this somewhere, need to track down)
- [x] Consolidate IANA Security Considerations (under consideration).  Would resolve #1405, and would also add an additional Security Consideration discouraging use of eval() to parse TDs, and would also pull in a bunch of assertions, making the S & P sections normative, and would also require adding cross-references.

The Security TF may add more after finishing our review.  Please do not merge until this is marked as complete (all checkboxes marked off above, draft status removed, WIP removed from title).

***
<a href="https://pr-preview.s3.amazonaws.com/mmccool/wot-thing-description/pull/1402.html" title="Last updated on Mar 17, 2022, 1:48 PM UTC (e185bf5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/1402/1d65bde...mmccool:e185bf5.html" title="Last updated on Mar 17, 2022, 1:48 PM UTC (e185bf5)">Diff</a>

### CODE REVIEW

**Comment by mmccool** [comment]
Should probably mention SQL injection under the area for "other markups" in Injection Attacks.  Since it's impossible to check for ALL possible markup languages in strings during TD validation that is not the answer.  USERS of strings drawn from TDs need to check for malicious values before using them.

**Comment by mmccool** [comment]
I would also like to change "Related to" to "Resolved" since I don't think we can add "HTML markup MUST not be used in strings" as a TD assertion; it won't solve the problem anyway.  This PR adds a note that HTML can't be depended upon to solve internationalization problems, since sanitization will disable it.

**Comment by mmccool** [comment]
Propose closing.  Can't check for all markup, PR #1402 say that HTML in strings can't be depended on (will normally be sanitized) and that's enough.

**Comment by mmccool** [comment]
Added requirement to resolve Issue #1405 (assuming option 1, IANA -> S&P, but we could also use option 2, redundant considerations, which would be easier but redundantly redundant.)

**Review by Citrullin — APPROVED** [review]

**Comment by sebastiankb** [comment]
from today's TD call, decided to merge

**Pull request merged**
