### PR TITLE
Adding `$id` to JSON Schema

### PR DESCRIPTION
**Pull request by egekorkan**
I have also bumped the version of the schema, applied the changes to the TM Schema, added a note about the `$id` into index.template.html

Fixes https://github.com/w3c/wot-thing-description/issues/674

***
<a href="https://pr-preview.s3.amazonaws.com/egekorkan/wot-thing-description/pull/1368.html" title="Last updated on Feb 3, 2022, 10:10 PM UTC (1705430)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/1368/114644a...egekorkan:1705430.html" title="Last updated on Feb 3, 2022, 10:10 PM UTC (1705430)">Diff</a>

### CODE REVIEW

**Comment by mlagally** [comment]
This MR also contains some other changes. Are these bug fixes or new features?

**Comment by egekorkan** [comment]
Sorry I forgot to add non-normative label. The only change is the schema related things and the editors note at https://github.com/w3c/wot-thing-description/pull/1368/files#diff-20c762491016637ceac07ca2c6c28cc19333d98b482bac4d863ac95cf88e9b6bR5992

**Comment by sebastiankb** [comment]
from today's TD call:
- some changes were covered by PR https://github.com/w3c/wot-thing-description/pull/1366
- @egekorkan can you fix the conflicts or simple create a new PR which only covers the ¢id field

**Comment by egekorkan** [comment]
There were some weird merge conflicts but they are fixed now :+1:

**Review by sebastiankb — APPROVED** [review]

**Review by relu91 — APPROVED** [review]
There are still some minor issues:
- commit history pretty broken ( I would suggest to rebase the changes)
- `@context`, `default` and `exclusiveMinimum` changes from https://github.com/w3c/wot-thing-description/pull/1366

**Comment by sebastiankb** [comment]
from today's TD call decided to merge

**Pull request merged**
