### PR TITLE
remove title id from static files

### LINKED ISSUE #1957: `title` reference is not correctly linked
# WHAT

The `title` term in TD points to https://www.w3.org/2019/wot/td#title

However, clicking on this link does not take you to the "title" section (3.3.12) of the TD ontology document. 

It seems that the id of this section is `x3-3-12-title` (https://www.w3.org/2019/wot/td#x3-3-12-title).

# How

Fix the section id of 3.3.12 to `id="title"`.

### PR DESCRIPTION
**Pull request by egekorkan**
fixes #1957

Future fixes will be at #2013

### CODE REVIEW

**Comment by danielpeintner** [comment]
Note: this fixes the static HTML files. Anyhow, every time we re-generate the HTML with ReSpec we need to manually remove the automatically added `id="title"` for the header.

**Review by danielpeintner — APPROVED** [review]

**Comment by lu-zero** [comment]
An alternative is to prefix all the id for the Thing elements with `thing_` so we'd have `thing_index`.

**Comment by egekorkan** [comment]
> An alternative is to prefix all the id for the Thing elements with `thing_` so we'd have `thing_index`.

I would move this discussion to #2013 . We cannot do that for 1.1 ontologies since that will break implementations

**Comment by lu-zero** [comment]
I mean have respec generate the anchor this way, not changing anything on our side.

**Pull request merged**
