### PR TITLE
Add husky pre-commit for rendering

### PR DESCRIPTION
**Pull request by relu91**
This PR adds a convenient git hook to automatically render the documentation and the TmSchema at every commit. The idea is to reduce human errors when contributing to the spec. The script is an improved version of what we already have in https://github.com/w3c/wot-binding-templates/tree/main/.husky. It works also with a dirty stage, which means that you can partially stage the changes and the hook will generate the documentation accordingly. 

**Note**: to correctly initialize the hook you have to call `npm install` at least once in the root folder of the repository.

### CODE REVIEW

**Review by sebastiankb — APPROVED** [review]

**Comment by mmccool** [comment]
TD call June 22: we agreed that this can be marked as non-substantive to resolve the IPR issue.  After that, some more reviewers (Ege? Daniel?) would probably be a good idea.

**Comment by sebastiankb** [comment]
from today's TD call: since Ege still on vacation lets postpone the decision about this PR to next week

**Comment by danielpeintner** [comment]
@relu91 this PR solves https://github.com/w3c/wot-thing-description/issues/883 right?

**Review by egekorkan — APPROVED** [review]

**Comment by sebastiankb** [comment]
from today's TD call, decided to merge

**Pull request merged**
