### PR TITLE
Manifest

### PR DESCRIPTION
**Pull request by sebastiankb**
update text for manifest rel type

also see https://github.com/w3c/wot-thing-description/issues/1324

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/pull/1340.html" title="Last updated on Dec 21, 2021, 4:49 PM UTC (08169ea)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/1340/21ce84a...08169ea.html" title="Last updated on Dec 21, 2021, 4:49 PM UTC (08169ea)">Diff</a>

### CODE REVIEW

**Comment by benfrancis** [comment]
@sebastiankb The change to the manifest text looks good, but I think there may be a bunch of commits here that aren't meant to be in this PR? Does it need rebasing?

**Review by benfrancis — COMMENTED** [review]
@sebastiankb The change to the manifest text looks good, but I think there may be a bunch of commits here that aren't meant to be in this PR? Does it need rebasing?

**Review by benfrancis — COMMENTED** [review]
@sebastiankb The change to the manifest text looks good, but I think there may be a bunch of commits here that aren't meant to be in this PR? Does it need rebasing?

**Comment by sebastiankb** [comment]
from today's TD call:
- group agrees to update the manifest text as provided in the PR
- however, there are some other places which should be not merged since this will overwrite just recent changes
- new PR will be provided with the manifest text only

**Comment by sebastiankb** [comment]
from today's TD call:
- it was planed to merge this PR however I missed to create a new PR that only contains the changed text for the mainfest
- I will create this PR after the TD call and merge this so that we have this new text available in the new WD

**Comment by sebastiankb** [comment]
PR was replaced by https://github.com/w3c/wot-thing-description/pull/1389

**Pull request closed without merging**
