### PR TITLE
Minor Issue and English Review

### PR DESCRIPTION
**Pull request by mmccool**
Deal with a few minor issues identified in the last TD meeting, then do a review of the English.  In my commits I have tried to separate out these goals.   Read each commit message during review to see what each one tries to accomplish.

Minor issues addressed:
- Ed note right after the figures in the information model section explaining meaning of mandatory and optional both for attributes with default values and for security.
- add default value of "in" in basic security scheme in Example 2
- add a paragraph to explanation of example 1 describing security configuration
- add list of allowable rel attribute values for forms

### CODE REVIEW

**Comment by mmccool** [comment]
Not quite ready for merge; still working on English review.

**Comment by sebastiankb** [comment]
https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fw3c.github.io%2Fwot-thing-description&doc2=https%3A%2F%2Fcdn.rawgit.com%2Fmmccool%2Fwot-thing-description%2Fenglish-review-1%2Findex.html

**Comment by mmccool** [comment]
Thanks for the diff link.  l should mention though that the diff is not totally accurate; for example, in example 2, after the merge there will be only one "security" configuration... two appear in the diff for some reason.

**Comment by mmccool** [comment]
Another diff, after fixing some formatting issues in the examples:
https://services.w3.org/htmldiff?doc1=http%3A%2F%2Fw3c.github.io%2Fwot-thing-description%2F&doc2=https%3A%2F%2Frawgit.com%2Fmmccool%2Fwot-thing-description%2Fenglish-review-1%2Findex.html

**Comment by mmccool** [comment]
I should mention I also caught and fixed an actual coding problem in one of the examples above... it was using security definitions, but those are not defined (yet).

**Comment by sebastiankb** [comment]
Many thanks! 

@mkovatsc It's now ready for a final review.

**Pull request merged**
