### PR TITLE
Security extension example and namespaces

### PR DESCRIPTION
**Pull request by mmccool**
NOTE: this is based on top of PR https://github.com/w3c/wot-thing-description/pull/537, so includes those edits as well.

This PR addresses Issue https://github.com/w3c/wot-thing-description/issues/501.  It provides an example of how to use an extension to implement a new security scheme, using OAuth2 as an example. 

Also addresses https://github.com/w3c/wot-thing-description/issues/345,  https://github.com/w3c/wot-thing-description/issues/350, and https://github.com/w3c/wot-thing-description/issues/470.

NOTE: OAuth2 is important but is also likely to be removed from the specification due to lack of implementation experience.   So if we do remove it, this example can remain and still be valid (although we might have to remove the immediately preceding example).

### CODE REVIEW

**Comment by mmccool** [comment]
Originally I had an assertion defining a standard namespace for security schemes but decided to drop it and update the example to use an "example.org" URL.   We probably SHOULD define a standard namespace for security schemes but we can publish that separately and put it into a W3C NOTE (maybe the WoT Security Best Practices note).   So this PR really only includes an example.  In the end I decided to say nothing about the overlap of `@type` and `scheme`...

**Comment by mmccool** [comment]
Extended to also take care of Issue https://github.com/w3c/wot-thing-description/issues/470.

**Comment by takuki** [comment]
Does this mean that some level of JSON-LD processing will be needed to understand security schemes?

**Comment by mmccool** [comment]
Also addressed https://github.com/w3c/wot-thing-description/issues/350.
Replying to Taki's comments: JSON-LD processing will not be required to understand built-in schemes.  It will be needed to understand extensions, including extensions defining security schemes.   Which is why it is still a good idea to have built-in schemes.  I suppose an implementation could take a middle ground though and understand "well-known" security schemes.   We could publish a bunch in a note...

**Comment by mmccool** [comment]
Also fixed https://github.com/w3c/wot-thing-description/issues/345

**Comment by mmccool** [comment]
An HTML diff: https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fcdn.staticaly.com%2Fgh%2Fw3c%2Fwot-thing-description%2FTD-TAG-review%2Findex.html%3Fenv%3Ddev&doc2=https%3A%2F%2Fcdn.staticaly.com%2Fgh%2Fmmccool%2Fwot-thing-description%2Fsecurity-extensions%2Findex.html%3Fenv%3Ddev

**Comment by mmccool** [comment]
OK to merge, but we will have to clean up the definition of extensions, perhaps in another document.  We will merge, @vcharpenay will define some issues, @mmccool will work on them and define a PR to discuss in the main call next week, and we can aim to merge any updates by the next TD call.

**Pull request merged**
