### PR TITLE
apply changes for the FPWD of ver 1.1 spec

### PR DESCRIPTION
**Pull request by ashimura**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/pull/1027.html" title="Last updated on Jan 12, 2021, 8:36 PM UTC (3747e90)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/1027/0f73bee...3747e90.html" title="Last updated on Jan 12, 2021, 8:36 PM UTC (3747e90)">Diff</a>

### CODE REVIEW

**Comment by sebastiankb** [comment]
From today's TD call: merge this PR

**Comment by gerardorn53** [comment]
Buenas

**Comment by gerardorn53** [comment]
Buenos

**Comment by egekorkan** [comment]
¿Hola?

- Propose deleting comments above as scam. Similar case at https://github.com/w3c/webappsec-mixed-content/pull/38

**Pull request merged**
