### PR TITLE
fixes #1247 to allow type to be an array

### LINKED ISSUE #1247: Allowing `type` to be an array
Not sure how I did not see this before but the validation keyword `type` in JSON Schema can be an array to denote the valid types. The following is a valid JSON Schema:
```json
{ "type": ["number", "string"] }
```
It means the number and string are accepted. This is same as saying:
```json
{
  "oneOf":[
    { "type":"string" },{ "type":"number" }
  ]
}
```
However, we allow the type to be only a string. This is a discrepancy that should be resolved in V1.1 in my opinion.

### PR DESCRIPTION
**Pull request by egekorkan**
***
<a href="https://pr-preview.s3.amazonaws.com/egekorkan/wot-thing-description/pull/1254.html" title="Last updated on Nov 3, 2021, 3:55 PM UTC (cd2a52b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/1254/f848688...egekorkan:cd2a52b.html" title="Last updated on Nov 3, 2021, 3:55 PM UTC (cd2a52b)">Diff</a>

### CODE REVIEW

**Comment by sebastiankb** [comment]
#1254

**Comment by sebastiankb** [comment]
from today's TD call we should not merge this for the TD 1.1 version since it breaks parser processors

**Comment by egekorkan** [comment]
I thought we did not want to merge this. I cannot find revert button probably since I don't have the editor-level access.

**Comment by sebastiankb** [comment]
@ashimura can you help here? This was not intended to. 

If this is not working we should create another PR to revert the changes

**Pull request merged**
