### PR TITLE
init tmRef 

### PR DESCRIPTION
**Pull request by sebastiankb**
also see #1081

- [x] introduction 
- [x] assertion about the copy mechanism
- [x] assertion about context type of tmRef
- [x] complex example

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/pull/1090.html" title="Last updated on Apr 21, 2021, 2:07 PM UTC (cb25206)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/1090/24c2bf8...cb25206.html" title="Last updated on Apr 21, 2021, 2:07 PM UTC (cb25206)">Diff</a>

### CODE REVIEW

**Comment by JKRhb** [comment]
Thank you for adding this feature! It already looks very solid to me. I have one question, though: Should it be possible to import an definition from a TM that itself is extended or imported ? If so, maybe one sentence could be added to clarify to procedure when importing from such a TM (for example "all extensions and imports in the referenced TM have to be resolved before importing a definition").

**Comment by sebastiankb** [comment]
I think, this makes sense. The process should be also explained when a TD are initiated from a TM (@relu91 maybe something also for #1095).

**Comment by JKRhb** [comment]
> 
> 
> I think, this makes sense. The process should be also explained when a TD are initiated from a TM (@relu91 maybe something also for #1095).

Great, thank for your feedback on this!

One more thing: In SDF, you can override and extend imported definitions. In [section 6.2.1](https://tools.ietf.org/html/draft-ietf-asdf-sdf-05#section-6.2.1) of the current draft the following example is given:

```json
"sdfData":
     "length" : {
       "type": "number",
       "minimum": 0,
       "unit": "m",
       "description": "There can be no negative lengths."
     }
   ...
     "cable-length" : {
       "sdfRef": "#/sdfData/length",
       "minimum": 0.05,
       "description": "Cables must be at least 5 cm."
     }
```

I suppose this should also be possible in the case of TMs? If so, maybe a clarification and a similar example could be given in the WoT specification?

**Comment by sebastiankb** [comment]
from today's TD call:
- not ready to merge
- we should support the [input](https://github.com/w3c/wot-thing-description/pull/1090#issuecomment-819530553) from Jan 
- in general we should point out that the 'semantic' should be not changed when overwrite definitions (e.g., do not change type string to number)

**Comment by sebastiankb** [comment]
from today's TD call: decide to merge this PR

**Pull request merged**
