### PR TITLE
Sync manual csv with playground and new titles

### PR DESCRIPTION
**Pull request by egekorkan**
The header has changed from Description to Assertion (in template.csv and assertions.csv) so I am adapting to it. Otherwise, no major addition or removal of individual assertions

### CODE REVIEW

**Comment by mmccool** [comment]
Your new files have the slight problem that when an assertion goes over more than one line, you have combined them without a space, so words are getting run together.  You should convert newlines to spaces.  It's also a good idea to get rid of leading spaces, trailing spaces, convert tabs to spaces, and convert multiple spaces to one space (all junk I had to do when I generated template.csv...)

**Comment by mmccool** [comment]
Note that my tooling only cares about ID and Status and ignores the other columns.

**Comment by mmccool** [comment]
I will pull the regexes from my implementation so you can clean this up...

**Comment by egekorkan** [comment]
The regex should go here: https://github.com/w3c/wot-thing-description/blob/main/testing/extractFile.js

Also once you put that, this issue will be hopefully fixed: https://github.com/w3c/wot-thing-description/issues/1742

**Comment by mmccool** [comment]
See PR #1756; not sure which one you want to merge first (might get conflicts in assertions.csv but these can be corrected by regenerating the file).

**Comment by egekorkan** [comment]
> See PR #1756; not sure which one you want to merge first (might get conflicts in assertions.csv but these can be corrected by regenerating the file).

@mmccool thank you for the other PR. The other one needs to merged first, I will come back to it afterwards.

**Comment by egekorkan** [comment]
I have checked after the testfest and there is no new changes other than this here

**Pull request merged**
