### PR TITLE
Update Security and Privacy Considerations

### LINKED ISSUE #1363: Split "9. Security and Privacy Considerations" into two sections?
from @danielpeintner (also see https://github.com/w3c/wot-thing-description/pull/1359):

Note: we do have 2 remaining issues 

grafik

Properly fixing it would require to split  [9. Security and Privacy Considerations](https://w3c.github.io/wot-thing-description/#sec-security-consideration) into **two** sections 
* Privacy Considerations
* Security Considerations

I don't think we should do that in the current state. We could also simply ignore this check.
Any thoughts?

### PR DESCRIPTION
**Pull request by mmccool**
Currently a placeholder for WIP - do not merge.
* Resolves https://github.com/w3c/wot-thing-description/issues/1348
* Resolves #1363

***
<a href="https://pr-preview.s3.amazonaws.com/mmccool/wot-thing-description/pull/1360.html" title="Last updated on Feb 7, 2022, 2:52 PM UTC (1c038a7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/1360/114644a...mmccool:1c038a7.html" title="Last updated on Feb 7, 2022, 2:52 PM UTC (1c038a7)">Diff</a>

### CODE REVIEW

**Comment by sebastiankb** [comment]
please also consider https://github.com/w3c/wot-thing-description/issues/1363

**Comment by mmccool** [comment]
Updated to implement split into two sections, security and privacy considerations.  Note: the id's still all contain "sec-security-considerations".  I'll probably update the ids as well but only after I check that there I won't break any links (at least *within* the document...).

**Comment by j1y3p4rk** [comment]
I reviewed it, and the privacy part is well written. 

In the security consideration part, I have minor change requests. 

In 9.1 TD Interception and Tempering Security Risk- mitigation part, "mutual authenticated channels" --> "mutual authenticated **secure** channels" because actually mutual authentication does not help to mitigate MITM attack but secure (encrpyted) channel established after mutual authentication does. 

With the same reason, I would like to ask to change in the chapter 9.2 Context Interception and Tempering Security Risk - Mitigation part, "obtained through authenticated channels" --> "obtained through secure channels established by mutual authenication" something like that..

If discussion is needed, we can do that in the security call.

**Comment by mmccool** [comment]
- Probably need a generic security consideration around mitigating all [OWASP Top 10 security](https://owasp.org/Top10/)issues (see also Discovery)

**Comment by mmccool** [comment]
> please also consider #1363

Done

**Comment by mmccool** [comment]
I went ahead and added the following sentence to the end of 9.2:
"If it is necessary to fetch a context file, an implementation may also attempt to use HTTPS (HTTP over TLS) even when only an HTTP URL is given."
Please comment if you feel this is a bad idea and I can revert.  A lot of the time use of an http URL is just a convention (a standardized "name" for the context) and when actually fetching content is it expected/permitted to upgrade security measures.

**Comment by mmccool** [comment]
I wonder also if somewhere in the TD spec (need to check if the JSON-LD spec already says this) it should say that HTTP and HTTPS URLs, if otherwise the same, are assumed to describe the same context.  Note the TD spec itself uses HTTPS context URLs (and really, we do want to avoid downgrading that to HTTP by accident, so a validator should reject HTTP versions, so this has to be worded that an *upgrade* is permitted, not that they are equivalent).

**Comment by sebastiankb** [comment]
from today's TD call:
- group decided to merge this PR and have this for the WD 
-  it is not completed yet, after the WD release there will be further updates
- we need to resolve the conflict before before merge, @mmccool work on this and will merge it later 
-

**Comment by danielpeintner** [comment]
Shall this PR be closed since https://github.com/w3c/wot-thing-description/pull/1387 has been merged?

**Comment by mmccool** [comment]
Closing, replaced with PR #1387

**Pull request closed without merging**
