### PR TITLE
Improve descriptions of apikey and psk security schemes

### PR DESCRIPTION
**Pull request by mmccool**
To resolve issue https://github.com/w3c/wot-thing-description/issues/998

Notes: 
1. The wotsec.ttl file has been updated, and rendering of index.html updated.
2. Will treat the problem of non-query URI templates separately and orthogonally (discussed in issue https://github.com/w3c/wot-thing-description/issues/923)
3. An example would be useful, as requested in issue https://github.com/w3c/wot-thing-description/issues/922.  Not handled in this PR, however.
4. td-validation.ttl also updated, although it seems redundant.  It would be helpful to clarify which is the master.

***
<a href="https://pr-preview.s3.amazonaws.com/mmccool/wot-thing-description/pull/1031.html" title="Last updated on Jan 25, 2021, 11:57 PM UTC (20f91c3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/1031/091d6a0...mmccool:20f91c3.html" title="Last updated on Jan 25, 2021, 11:57 PM UTC (20f91c3)">Diff</a>

### CODE REVIEW

**Comment by mmccool** [comment]
- Added copies of descriptions of apikey and psk to td-validation.ttl.  Which is the master?   The render script does not make clear.   It would be nice to not have to enter things twice.
- Render script seems to be broken, getting a syntax error in the included file.  Waiting for a fix.  Until this is fixed the changes will not get reflected in the index.html file. In the meantime, reviewers should look at the text in ontology/wotsec.ttl for the apikey and psk schemes.

**Comment by mmccool** [comment]
Marking as "ready for review" but "not ready for merging".

**Comment by mmccool** [comment]
@oliverpfaff notes that there is an IETF RFC for security terminology we should cite, but unfortunately it does not define either "API Key" (which is a "marketing" term...) but more surprisingly (since it is used in other RFCs like TLS-PSK) does not define "PSK" or "pre-shared key".

**Comment by mmccool** [comment]
Rendering error seems to have been fixed now but new text still not showing up, so I'm probably not making the edit in the right place... will try to fix in/for the TD call, in the meantime please do try to provide feedback on the proposed text.  I plan to reword the last sentence in the PSK spec to make is sound less like an assertion (it really should be, but testing would be difficult, so...)

**Comment by egekorkan** [comment]
This looks good and has the content that I would look for when I am seeing these terms for the first time

**Comment by sebastiankb** [comment]
From today's TD call:
- the content looks good
- however, PR not ready yet, needs some render script check (@vcharpenay can you help here?)
- PR maybe ready to merge next week

**Comment by danielpeintner** [comment]
>     * however, PR not ready yet, needs some render script check (@vcharpenay can you help here?)

I did look into the the "issue" and my local rendering does work just fine. I think the updated content is in index.html.
Maybe you want trying to re-run the render script.


[index.zip](https://github.com/w3c/wot-thing-description/files/5847792/index.zip)

**Comment by mmccool** [comment]
* Thanks, I'll try the rendering again.  I assume a bug got fixed...
* In the discussion in the TD call and in the security call, we agreed that an assertion prohibiting putting secret keys in the TD would be useful.  It can't easily be tested, but can be manually asserted, and gives us a way to say that people who put secret keys in a TD are not compliant with the specification.   I plan to structure this as a single blanket assertion rather than assertions in particular schemes (so it is prohibited, using the MUST NOT RFC2119 keyword, for *all* schemes, current and future).   Wording of the assertion, to be added to the header section for all security schemes, to be as follows: "For all security schemes, private keys, passwords, or other sensitive information directly providing access should be shared and stored out-of-band and MUST NOT be stored in the TD."  This would be followed by the informative statement: "The purpose of the TD is to describe how to access the system if a consumer has authorization, not to grant that authorization."

**Comment by mmccool** [comment]
Rendering fixed, changes discussed above implemented.  Ready to merge.

**Comment by egekorkan** [comment]
One thing I have realized is that the API Key says that it can be in a proprietary format. Thus, wouldn't we need a keyword called format (or similar) that can be used to convey this information. Otherwise, one would need documentation on that format via out-of-band-information. The string value can be left open or constrained to a set of values if such formats are explored.

**Comment by sebastiankb** [comment]
from today's TD call we will merge this PR.

**Pull request merged**
